# Build and deploy ASP.Net Core app to Azure Web App: web-easymoto-rm557177
name: Build and deploy ASP.Net Core app to Azure Web App: web-easymoto-rm557177

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: web-easymoto-rm557177
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: src/EasyMoto.Api/EasyMoto.Api.csproj
  PUBLISH_DIR: ./publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --no-restore -c Release

      - name: Publish API
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_DIR }}

      - name: List published files (debug)
        run: ls -la ${{ env.PUBLISH_DIR }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_442117ad630c425bb5d0aa51fd4acdcd }}
          package: ${{ env.PUBLISH_DIR }}
