name: 'Build and deploy ASP.NET Core app to Azure Web App: web-easymoto-rm557177'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: web-easymoto-rm557177
  PROJECT_PATH: src/EasyMoto.Api/EasyMoto.Api.csproj
  PUBLISH_DIR: publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build (Release)
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore -c Release

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ github.workspace }}/${{ env.PUBLISH_DIR }}

      - name: List published files (debug)
        run: ls -la ${{ github.workspace }}/${{ env.PUBLISH_DIR }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: production
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_442117ad630c425bb5d0aa51fd4acdcd }}
          package: ${{ github.workspace }}/${{ env.PUBLISH_DIR }}
